version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - mvn-repo-{{ .Branch }}-{{ checksum "pom.xml" }}
            - mvn-repo-{{ .Branch }}-
            - mvn-repo-
      - run:
          name: Download Dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: mvn-repo-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: mvn clean package
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build