version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      # Replace these environment variables with your actual GitHub credentials
      - run:
          name: Set up Git
          command: |
            git config --global user.email "mahdinezhadasd@gmail.com"
            git config --global user.name "mahdi"
            # git remote set-url origin https://github.com/mahdinezhadasad/microservices

      - run:
          name: Fetch changes
          command: git fetch origin --recurse-submodules=no --progress --prune

      # Add and commit changes
      - run:
          name: Add changes
          command: git add --all

      - run:
          name: Commit changes
          command: git commit -m "Commit message"

      # Push changes
      - run:
          name: Push changes
          command: git push origin master